"""
data_venues.py
--------------
All 16 FIFA World Cup 2026 host venues with full details.
Source: worldcupwiki.com/stadiums (verified May 2026).

Fields per venue:
  name          - common commercial name
  fifa_name     - official FIFA tournament name (no sponsors allowed)
  city          - host city
  country       - host country
  capacity      - tournament capacity
  matches       - number of matches hosted
  roof          - roof type
  nfl_tenant    - NFL/MLS/CFL club that normally plays here (None if N/A)
  opened        - year originally opened
  region        - FIFA scheduling region (Western / Central / Eastern)
  lat / lon     - coordinates for mapping
  match_nos     - list of official FIFA match numbers played here
"""

VENUES = [

    # =========================================================================
    # UNITED STATES — 11 venues, 78 matches
    # =========================================================================

    {
        "name":       "MetLife Stadium",
        "fifa_name":  "New York New Jersey Stadium",
        "city":       "East Rutherford",
        "state":      "New Jersey",
        "country":    "USA",
        "capacity":   82_500,
        "matches":    8,
        "roof":       "Open",
        "nfl_tenant": "New York Giants / New York Jets",
        "opened":     2010,
        "region":     "Eastern",
        "lat":        40.8135,
        "lon":        -74.0745,
        "notes":      "Hosts the Final (M104). First ever World Cup halftime show.",
        "match_nos":  [6, 17, 43, 56, 67, 77, 91, 104],
    },
    {
        "name":       "SoFi Stadium",
        "fifa_name":  "Los Angeles Stadium",
        "city":       "Inglewood",
        "state":      "California",
        "country":    "USA",
        "capacity":   70_240,
        "matches":    8,
        "roof":       "Translucent fixed canopy (no AC)",
        "nfl_tenant": "Los Angeles Rams / Los Angeles Chargers",
        "opened":     2020,
        "region":     "Western",
        "lat":        33.9535,
        "lon":        -118.3392,
        "notes":      "Most expensive stadium ever built ($5.5bn). Hosts USA opener vs Paraguay.",
        "match_nos":  [4, 16, 26, 38, 59, 73, 84, 98],
    },
    {
        "name":       "AT&T Stadium",
        "fifa_name":  "Dallas Stadium",
        "city":       "Arlington",
        "state":      "Texas",
        "country":    "USA",
        "capacity":   92_967,
        "matches":    9,
        "roof":       "Retractable",
        "nfl_tenant": "Dallas Cowboys",
        "opened":     2009,
        "region":     "Central",
        "lat":        32.7473,
        "lon":        -97.0945,
        "notes":      "Largest venue at the tournament. Most matches (9). Hosts SF (M101).",
        "match_nos":  [10, 22, 41, 57, 72, 78, 88, 93, 101],
    },
    {
        "name":       "Mercedes-Benz Stadium",
        "fifa_name":  "Atlanta Stadium",
        "city":       "Atlanta",
        "state":      "Georgia",
        "country":    "USA",
        "capacity":   71_000,
        "matches":    8,
        "roof":       "Retractable",
        "nfl_tenant": "Atlanta Falcons / Atlanta United FC",
        "opened":     2017,
        "region":     "Central",
        "lat":        33.7553,
        "lon":        -84.4006,
        "notes":      "Hosts SF (M102). Grass installed Jan 2026 replacing artificial turf.",
        "match_nos":  [13, 25, 37, 52, 70, 80, 95, 102],
    },
    {
        "name":       "Levi's Stadium",
        "fifa_name":  "San Francisco Bay Area Stadium",
        "city":       "Santa Clara",
        "state":      "California",
        "country":    "USA",
        "capacity":   70_909,
        "matches":    6,
        "roof":       "Open",
        "nfl_tenant": "San Francisco 49ers",
        "opened":     2014,
        "region":     "Western",
        "lat":        37.4033,
        "lon":        -121.9694,
        "notes":      "Also hosted Super Bowl LX (Feb 2026). LEED Gold certified.",
        "match_nos":  [5, 20, 32, 44, 60, 81],
    },
    {
        "name":       "NRG Stadium",
        "fifa_name":  "Houston Stadium",
        "city":       "Houston",
        "state":      "Texas",
        "country":    "USA",
        "capacity":   72_220,
        "matches":    7,
        "roof":       "Retractable",
        "nfl_tenant": "Houston Texans",
        "opened":     2002,
        "region":     "Central",
        "lat":        29.6847,
        "lon":        -95.4107,
        "notes":      "First NFL stadium with a retractable roof. Critical for Houston summer heat.",
        "match_nos":  [9, 21, 33, 45, 63, 76, 90],
    },
    {
        "name":       "Arrowhead Stadium",
        "fifa_name":  "Kansas City Stadium",
        "city":       "Kansas City",
        "state":      "Missouri",
        "country":    "USA",
        "capacity":   76_640,
        "matches":    6,
        "roof":       "Open",
        "nfl_tenant": "Kansas City Chiefs",
        "opened":     1972,
        "region":     "Central",
        "lat":        39.0489,
        "lon":        -94.4839,
        "notes":      "Oldest venue at the tournament. Guinness Record: 142.2 dB crowd noise (2014).",
        "match_nos":  [19, 35, 58, 71, 87, 100],
    },
    {
        "name":       "Gillette Stadium",
        "fifa_name":  "Boston Stadium",
        "city":       "Foxborough",
        "state":      "Massachusetts",
        "country":    "USA",
        "capacity":   64_628,
        "matches":    7,
        "roof":       "Open",
        "nfl_tenant": "New England Patriots / New England Revolution",
        "opened":     2002,
        "region":     "Eastern",
        "lat":        42.0909,
        "lon":        -71.2643,
        "notes":      "$250m renovation 2023 added Lighthouse tower. Hosts QF (M97).",
        "match_nos":  [7, 18, 30, 46, 61, 74, 97],
    },
    {
        "name":       "Lincoln Financial Field",
        "fifa_name":  "Philadelphia Stadium",
        "city":       "Philadelphia",
        "state":      "Pennsylvania",
        "country":    "USA",
        "capacity":   69_328,
        "matches":    6,
        "roof":       "Open",
        "nfl_tenant": "Philadelphia Eagles",
        "opened":     2003,
        "region":     "Eastern",
        "lat":        39.9008,
        "lon":        -75.1675,
        "notes":      "Locally known as 'The Linc'. Already had natural grass — minimal changes needed.",
        "match_nos":  [11, 31, 42, 55, 68, 89],
    },
    {
        "name":       "Lumen Field",
        "fifa_name":  "Seattle Stadium",
        "city":       "Seattle",
        "state":      "Washington",
        "country":    "USA",
        "capacity":   68_740,
        "matches":    6,
        "roof":       "Open",
        "nfl_tenant": "Seattle Seahawks / Seattle Sounders FC",
        "opened":     2002,
        "region":     "Western",
        "lat":        47.5952,
        "lon":        -122.3316,
        "notes":      "Washington state invested $46.6m total. ~750,000 visitors expected in Seattle.",
        "match_nos":  [14, 29, 50, 65, 82, 94],
    },
    {
        "name":       "Hard Rock Stadium",
        "fifa_name":  "Miami Stadium",
        "city":       "Miami Gardens",
        "state":      "Florida",
        "country":    "USA",
        "capacity":   65_000,
        "matches":    7,
        "roof":       "Canopy",
        "nfl_tenant": "Miami Dolphins",
        "opened":     1987,
        "region":     "Eastern",
        "lat":        25.9580,
        "lon":        -80.2389,
        "notes":      "Hosts Bronze Final (M103). Already had natural Bermuda grass — no turf swap needed.",
        "match_nos":  [15, 39, 51, 69, 86, 99, 103],
    },

    # =========================================================================
    # MEXICO — 3 venues, 13 matches
    # =========================================================================

    {
        "name":       "Estadio Azteca",
        "fifa_name":  "Mexico City Stadium",
        "city":       "Mexico City",
        "state":      "Mexico City (CDMX)",
        "country":    "Mexico",
        "capacity":   87_500,
        "matches":    5,
        "roof":       "Partial canopy",
        "nfl_tenant": "Club America / Cruz Azul",
        "opened":     1966,
        "region":     "Central",
        "lat":        19.3029,
        "lon":        -99.1505,
        "notes":      "Only stadium to host 3 World Cups (1970, 1986, 2026). Hosts opening match (M1).",
        "match_nos":  [1, 24, 53, 79, 92],
    },
    {
        "name":       "Estadio BBVA",
        "fifa_name":  "Monterrey Stadium",
        "city":       "Monterrey",
        "state":      "Nuevo León",
        "country":    "Mexico",
        "capacity":   53_500,
        "matches":    4,
        "roof":       "Partial canopy",
        "nfl_tenant": "CF Monterrey (Rayados)",
        "opened":     2015,
        "region":     "Western",
        "lat":        25.6693,
        "lon":        -100.2436,
        "notes":      "Views of Cerro de la Silla mountain. Hosts M36: Tunisia vs Japan — 1,000th WC match.",
        "match_nos":  [12, 36, 54, 75],
    },
    {
        "name":       "Estadio Akron",
        "fifa_name":  "Guadalajara Stadium",
        "city":       "Zapopan",
        "state":      "Jalisco",
        "country":    "Mexico",
        "capacity":   48_000,
        "matches":    4,
        "roof":       "Partial canopy",
        "nfl_tenant": "CD Guadalajara (Chivas)",
        "opened":     2010,
        "region":     "Western",
        "lat":        20.6854,
        "lon":        -103.4674,
        "notes":      "Volcano-shaped design. Only venue with NO knockout stage matches.",
        "match_nos":  [2, 28, 48, 64],
    },

    # =========================================================================
    # CANADA — 2 venues, 13 matches
    # =========================================================================

    {
        "name":       "BMO Field",
        "fifa_name":  "Toronto Stadium",
        "city":       "Toronto",
        "state":      "Ontario",
        "country":    "Canada",
        "capacity":   45_736,
        "matches":    6,
        "roof":       "Open",
        "nfl_tenant": "Toronto FC (MLS)",
        "opened":     2007,
        "region":     "Eastern",
        "lat":        43.6333,
        "lon":        -79.4186,
        "notes":      "Smallest venue at tournament. $157.9m renovation expanded capacity from 30k. Hosts Canada opener.",
        "match_nos":  [3, 23, 34, 47, 62, 83],
    },
    {
        "name":       "BC Place",
        "fifa_name":  "BC Place Vancouver",
        "city":       "Vancouver",
        "state":      "British Columbia",
        "country":    "Canada",
        "capacity":   54_500,
        "matches":    7,
        "roof":       "Retractable",
        "nfl_tenant": "Vancouver Whitecaps FC (MLS) / BC Lions (CFL)",
        "opened":     1983,
        "region":     "Western",
        "lat":        49.2767,
        "lon":        -123.1115,
        "notes":      "Hosted 2010 Winter Olympics ceremonies & 2015 Women's WC Final. ~350,000 visitors expected.",
        "match_nos":  [8, 27, 40, 49, 66, 85, 96],
    },
]
